export const SET_REGISTER = 'SET_REGISTER';
export const SET_REGISTER_ERROR = 'SET_REGISTER_ERROR';

export const SET_AUTH = 'SET_AUTH';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

export const REMOVE_AUTH = 'REMOVE_AUTH';

export const PUSH_PAYMENT = 'PUSH_PAYMENT';
export const SET_PAYMENT_STATUS = 'SET_PAYMENT_STATUS';

export const PAYMENT_SUCCESS_INFO_DISABLE = 'PAYMENT_SUCCESS_INFO_DISABLE';
export const REMOVE_PAYMENT_SUCCESS_INFO = 'REMOVE_PAYMENT_SUCCESS_INFO';

export const SET_PAYMENT_DATA = 'SET_PAYMENT_DATA';

export const SET_ADDRESS = 'SER_ADDRESS';
export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST';
export const SET_ADDRESS_LOADING = 'SET_ADDRESS_LOADING';

export const SET_ROUTE = 'SET_ROUTE';
export const SET_ROUTE_COORDS = 'SET_ROUTE_COORDS';
