export const SET_REGISTER = 'SET_REGISTER';
export const SET_AUTH = 'SET_AUTH';
export const GET_AUTH_PROGRESS = 'GET_AUTH_PROGRESS';
export const GET_AUTH_STATUS = 'GET_AUTH_STATUS';

export const REMOVE_AUTH = 'REMOVE_AUTH';

export const PUSH_PAYMENT = 'PUSH_PAYMENT';
export const GET_PAYMENT_STATUS = 'GET_PAYMENT_STATUS';

export const PAYMENT_SUCCESS_INFO_DISABLE = 'PAYMENT_SUCCESS_INFO_DISABLE';
export const REMOVE_PAYMENT_SUCCESS_INFO = 'REMOVE_PAYMENT_SUCCESS_INFO';

export const GET_PAYMENT = 'GET_PAYMENT';
export const GET_PAYMENT_DATA = 'GET_PAYMENT_DATA';
